-- Create scans table for CropSense.AI database persistent history
create table public.scans (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete cascade,
  crop_name text not null,
  disease_name text not null,
  severity text not null,
  cause text not null default 'N/A',
  treatment text not null,
  image_url text not null default '',
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable Row Level Security (RLS) on public scans table
alter table public.scans enable row level security;

-- Allow users to insert their own scans
create policy "Users can insert own scans" on public.scans
  for insert with check (auth.uid() = user_id);

-- Allow users to read only their own scans
create policy "Users can view own scans" on public.scans
  for select using (auth.uid() = user_id);

-- Allow service-role (backend) unrestricted access for server-side inserts via anon key
-- NOTE: If using the anon key in your backend, grant the anon role access:
create policy "Allow anon inserts" on public.scans
  for insert to anon with check (true);

create policy "Allow anon reads" on public.scans
  for select to anon using (true);
