-- Create scans table for CropSense.AI database persistent history
create table public.scans (
  id bigint generated by default as identity primary key,
  crop_name text not null,
  disease_name text not null,
  severity text not null,
  cause text not null default 'N/A',
  treatment text not null,
  image_url text not null default '',
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable Row Level Security (RLS) on public scans table
alter table public.scans enable row level security;

-- Create policy to allow public inserts
create policy "Allow public inserts" on public.scans 
  for insert with check (true);

-- Create policy to allow public select reads
create policy "Allow public reads" on public.scans 
  for select using (true);
